<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ConsigneesSeeder extends Seeder
{
    public function run(): void
    {
        $consignees = [
            ['consignee_name' => 'Nutriello International', 'consignee_address' => 'Plot No. 183, Deenanath Ji Ka Rasta,Barathio, Ki Gali Chandpole, Bazar Jaipur, chandpole bazar, Jaipur, Rajasthan, India', 'consignee_phone' => '+918890430290'],
            ['consignee_name' => 'VIRKINE TRADEXIM PRIVATE LIMITED', 'consignee_address' => 'BUILDING N0.2/ 2 AND 2/ 1 4TH FLOOR, CHHATARPUR MAIN, ROAD, NEW DELHI INDIA', 'consignee_phone' => '+918586921182'],
            ['consignee_name' => 'DATES FACTORY', 'consignee_address' => '1789, GROUND FLOOR,, ZEENAT MAHAL BAZAR LAL KUAN NEW DELHI, DELHI, NORTH DELHI, DELHI', 'consignee_phone' => '+919654949177'],
            ['consignee_name' => 'PT AGRO GUNAJAYA SENTOSA', 'consignee_address' => '– KLAMPIS (KPP GUBENG) RUKO KLAMPIS MEGAH, JL. KLAMPIS JAYA BLOK B-20 KLAMPIS NGASEM, KEC. SUKOLILO SURABAYA, EAST JAVA INDONESIA TAXNO: 1000 0000 0120 3093 agrogunajayasentos@gmail.com', 'consignee_phone' => '085885555888'],
            ['consignee_name' => 'Arissa International', 'consignee_address' => 'Office No. 2, Blue Moon Chambers, 25 Medow Street, Fort, Mumbai-23, India ', 'consignee_phone' => '+918044566957'],
            ['consignee_name' => 'P.D TRADELINK', 'consignee_address' => 'F-41 APMC MARKET-1 PHASE II, SECTOR 19, VASHI NAVI MUMBAI INDIA', 'consignee_phone' => '+919867646944'],
            ['consignee_name' => 'KNIGHT TRADING COMPANY', 'consignee_address' => 'KNIGHT TRADING COMP ANY 499-500, KATRA ISHW AR BHA WAN KHARI BAOLI, DELHI INDIA IECNO: 0595032745 PANNO: AAJPK8789D GSTNO: 07AAJPK8987D1Z8 CONTRACT 9560020114 , KNIGHT TRADING COMP ANY 499-500, KATRA ISHW AR BHA WAN KHARI BAOLI, DELHI-110006 INDIA 0595032745 AAJPK8789D 07AAJPK8987D1Z8 CONTRACT 9560020114', 'consignee_phone' => ''],
            ['consignee_name' => 'DRAPS VENTURES PRIVATE LIMITED', 'consignee_address' => 'Company Name : DRAPS VENTURES PRIVATE LIMITED ', 'consignee_phone' => '9930728435'],
            ['consignee_name' => 'HT IMPORT AND EXPORT', 'consignee_address' => '1117 SECOUND FLOOR GANDHI GALI FATEHPURI DELHI INDIA.', 'consignee_phone' => '8595824445'],
            ['consignee_name' => 'J.H.B IMPORTS', 'consignee_address' => 'MAJITH MANDI, AMRITSAR, (PUNJAB) INDIA. ', 'consignee_phone' => '+917009187601'],
            ['consignee_name' => 'M/S SIDHI VINAYAK INTERNATIONAL', 'consignee_address' => '27 GANDHI GALI FATEH PURI DELHI ', 'consignee_phone' => '9910543618'],
            ['consignee_name' => 'K.B.S. ENTERPRISES', 'consignee_address' => 'K.B.S ENTERPRISES 619-20 KATRA ISHWAR BHAWAN KHARI BAOLI DELHI INDIA.', 'consignee_phone' => '01140532467'],
            ['consignee_name' => 'RAJA DRY FRUITS', 'consignee_address' => 'Raja dry fruit Address: First Floor, 602-603,Katra Ishwar Bhawan, Khari Baoli, North Delhi, Delhi – GS , First Floor, 602-603,Katra Ishwar Bhawan, Khari Baoli, North Delhi, Delhi – 110006 GS , 584-B, Katra Ishwar Bhawan, Khari Baoli, North Delhi, Delhi – 110006 GS', 'consignee_phone' => '9811526548'],
            ['consignee_name' => 'HINDIA TRADING CO', 'consignee_address' => 'GODOWN NO J 15 APMC MASALA MARKET 1 PHASE 2, SECTOR 19, NAVI MUMBAI, THANE, MAHARASHTRA INDIA.', 'consignee_phone' => '+919022333335'],
            ['consignee_name' => 'DIPAK TRADING CO.', 'consignee_address' => 'GROUND FLOOR, F-29, MARKET-1, PHASE-2 APMC, SECTOR -19, VASHI, TURBHE, NAVI MUMBAI, THANE MAHARASHTRA INDIA', 'consignee_phone' => '+9328046601'],
            ['consignee_name' => 'MANAV ARORORA (HUF)', 'consignee_address' => '', 'consignee_phone' => '9811133716'],
            ['consignee_name' => 'REHMAT OVERSEAS', 'consignee_address' => '553 KATRA ISHWAR BHAWAN KHARI BAOLI DELHI INDIA.', 'consignee_phone' => '9810116604'],
            ['consignee_name' => '18TH WONDER FOODS LLP', 'consignee_address' => '18/B.Mohan Lal Street, Shyambazar,Kolkata,Kolkata, West Bengal', 'consignee_phone' => '+919331087253'],
            ['consignee_name' => 'ANANT SEEDS', 'consignee_address' => 'PLOT NO- 1. R S NO. 356/2. JUNAGADH HIGHWAY, AGATRAI, JUNAGADH. GUJARAT. GUJARAT. INDIA', 'consignee_phone' => '+919825236931'],
            ['consignee_name' => 'Satgun Exim LLP', 'consignee_address' => '', 'consignee_phone' => '+919890700377'],
            ['consignee_name' => 'HUNNY ENTERPRISES', 'consignee_address' => 'SHOP NO: 25, GANDHI GALI, FATEHPURI DELHI INDIA, , SHOP NO: 25, GANDHI GALI, FATEHPURI DELHI 110006 INDIA', 'consignee_phone' => '9654155525'],
            ['consignee_name' => 'CHAMAN TRADING CORPORATION', 'consignee_address' => '074-75 GANDHI GALI KHARI BAOLI FATEHPURI NORTH DELHI INDIA.', 'consignee_phone' => '9891803804'],
            ['consignee_name' => 'S.P INTERNATIONAL', 'consignee_address' => '412-A NAYA BANS KHARI BAOLI DELHI INDIA.', 'consignee_phone' => '+919810644040'],
            ['consignee_name' => 'SAMARTH TRADING COMPANY', 'consignee_address' => 'Customer Care Details ', 'consignee_phone' => '+917303989402'],
            ['consignee_name' => 'MANIK TRADERS', 'consignee_address' => 'D-25 APMC MARKET-1 PHASE-2 SECTOR-19 VASHI NAVI MUMBAI INDIA. , D-25 APMC MARKET-1 PHASE-2 SECTOR-19 VASHI NAVI MUMBAI 400705 INDIA', 'consignee_phone' => '9764265544'],
            ['consignee_name' => 'SIP ENTERPRISES', 'consignee_address' => '27 KATRA ISHWAR BHAWAN KHARI BAOLI DELHI INDIA. GS', 'consignee_phone' => '9810141001'],
            ['consignee_name' => 'MANOCHA ENTERPRISES', 'consignee_address' => 'FOR COMBINED TRANSPORT SHIPMENT OR PORT SHIPMENT 26 GROUND FLOOR KATRA ISHWAR BHAWAN GANDHI GALI KHARI BAOLI DELHI INDIA.', 'consignee_phone' => '05881063999810355677'],
            ['consignee_name' => 'KAILASH TRADERS', 'consignee_address' => '535/2, KATRA ISHWAR BHAWAN, KHARI BAOLI, DELHl', 'consignee_phone' => '01145680700'],
            ['consignee_name' => 'BAKHSHI GLOBAL INC.', 'consignee_address' => '190 Britannia Road East, Unit 16, No. 1 Mississauga, Ontario, Canada L4Z 2E7 ', 'consignee_phone' => '+14379925262'],
            ['consignee_name' => 'K R Trading Corporation', 'consignee_address' => '1026/14,Gagerna House,Gali Teliyan, Tilak Bazar, Delhi M.NO.9990764574 GS', 'consignee_phone' => '9990764574'],
            ['consignee_name' => 'OMNISUN GSS INDIA PRIVATE LTD', 'consignee_address' => 'OFFICE NO. 433 AVIOR CORPORATE PARK LBS MARG MULUND WEST MUMBAI MULUND WEST INDIA.', 'consignee_phone' => '+918097757170'],
            ['consignee_name' => 'SAFFRON HOME LLP', 'consignee_address' => 'GROUND FLOOR, SHOP A, 18 KIRANA BHAWAN, AUDIAPPA NAICKEN STREET, SOWCARPET, CHENNAI TAMILNADU INDIA. , GROUND FLOOR, SHOP A, 18 KIRANA BHAWAN AUDIAPPA NAICKEN STREET, SOWCARPET, CHENNAI 600001 TAMILNADU INDIA.', 'consignee_phone' => '9840526511'],
            ['consignee_name' => 'SUKHA SINGH SWARAN SINGH', 'consignee_address' => '25, KATRA ISHWAR BHAWAN, KHARI BAOLI DELHI INDIA.', 'consignee_phone' => '9990005047'],
            ['consignee_name' => 'G.T INDIA PVT LTD', 'consignee_address' => 'NO: 81 & 83 DR ALAGAPPA ROAD PURASAIWALKАM CHENNAI INDIA. , NO: 81 & 83 DR ALAGAPPA ROAD PURASAIWALKAM CHENNAI 600084 INDIA. , GT INDIA PVT LTD GT HOUSE ,No 81& 83 Dr Alagappa Road, Purasaiwalkam,Chennai-600084 , Tamil Nadu.', 'consignee_phone' => '04443758595'],
            ['consignee_name' => 'LEELA GOPAL INTERNATIONAL', 'consignee_address' => '513/2 KATRA ISHWAR BHAWAN KHARI BAOLI DELHI INDIA., 513/2 KATRA ISHWAR BHAWAN KHARI BAOLI DELHI 110006 INDIA. , 513/2, Katra Ishwar Bhawan Khari Baoli, New Delhi-110006.', 'consignee_phone' => '+919999927864'],
            ['consignee_name' => 'MEHRA DRY FRUIT IMPEX', 'consignee_address' => '1074/75 GANDHI GALI FATEHPURI NEW DELHI INDIA., 1074/75 GANDHI GALI FATEHPURI NEW DELHI 110006 INDIA GSTNO: 07CPUPM4144Q1ZY', 'consignee_phone' => '+9311076797'],
            ['consignee_name' => 'SIDDHARTH IMPORTS PVT LTD', 'consignee_address' => '581 KATRA ISHWAR BHAWAN KHARI BAOLI DELHI INDIA.', 'consignee_phone' => '+919810193840'],
            ['consignee_name' => 'CASTROL EXPORT INDUSTRIES', 'consignee_address' => 'B/H HUNDAI SHOWROOM, OPP. OCTROI NAKA, NEAR CHECK POST, RAJKOT, HIGHWAY, SABALPUR, JUMAGADH, GUJARAT INDIA. CODE (, B/H HUNDAI SHOWROOM OPP, OCTROI NAKA, NEAR CHECK POST, RAJKOT HIGHWAY SABALPUR, JUMAGADH. GUJARAT- 362037 CODE (', 'consignee_phone' => '+919924434600'],
            ['consignee_name' => 'DIVYANSHI ENTERPRISES', 'consignee_address' => '104 SAMURAI BHAWAN SOP NO: 3 DEENANATH JI KI GALI CHANDPOLE BAZAR JAIPUR (RAJASTHAN) INDIA', 'consignee_phone' => '9929273994'],
            ['consignee_name' => 'KOTHARI BROTHERS', 'consignee_address' => '⁠ ADD: E/45 APMC MARKET-1 PHASE-2 VASHI NAVI MUMBAI INDIA. , E/45 APMC MARKET-1 PHASE-2 VASHI NAVI MUMBAI 400705 INDIA.', 'consignee_phone' => '+919820521493'],
            ['consignee_name' => 'SHREE RADHEY KRISHNA INTERNATIONAL.', 'consignee_address' => '2ND FLOOR 616 KATRA ISHWAR BHAWAN KHARI BAOLI DELHI INDIA. , SHREE RADHEY KRISHNA INTERNATIONAL 2ND FLOOR 616 KATRA ISHWAR BHAWAN KHARI BAOLI DELHI 110006 INDIA.', 'consignee_phone' => '01143305048'],
            ['consignee_name' => 'BALRAJ KUMAR VINOD KUMAR', 'consignee_address' => '76 B GADODIA MARKET, KHARI BAOLI, DELHI INDIA., 76 B GADODIA MARKET, KHARI BAOLI, DELHI 110006 INDIA.', 'consignee_phone' => '9871475767'],
            ['consignee_name' => 'SHIV LAL AMOG KUMAR', 'consignee_address' => '522 KATRA ISHWAR BHAWAN KHARI BAOLI NEW DELHI INDIA. , 522 KATRA ISHWAR BHAWAN KHARI BAOLI NEW DELHI 110006 INDIA', 'consignee_phone' => '+919811508994'],
            ['consignee_name' => 'ELECO GENERAL TRADING L.L.C', 'consignee_address' => 'HAJI YOUSAF HUSSAIN SADIQ BUILDING, SHOP NO.7 AL RAS, DUBAI, UAE ', 'consignee_phone' => ''],
            ['consignee_name' => 'YAAQOUB HAMDAN FOODSTUFF TRADING CO LLC', 'consignee_address' => 'SHOP NO: 28 AL HAWAI BUILDING AL RAS STREET DEIRA DUBAI UAE ', 'consignee_phone' => ''],
            ['consignee_name' => 'M L G IMPEX', 'consignee_address' => '522 KATRA ISHWAR BHAWAN KHARI BAOLI DELHI CENTRAL DELHI 110006 INDIA', 'consignee_phone' => '8800764612'],
            ['consignee_name' => 'MAADHAV TRADING COMPANY', 'consignee_address' => '1074/75/7-GF GANDHI GALI JYOTI MARKET KHARI BAOLI NORTH DELHI INDIA. , MADHAV TRADING COMPANY 1074/75/7 - GF GANDHI GALI JYOTI MARKET KHARI BAOLI NORTH DELHI 110006 INDIA.', 'consignee_phone' => '+911140109800'],
            ['consignee_name' => 'ORANJ INDIAA', 'consignee_address' => '195-A LANE W-11 WESTERN AVENUE SAINIK FARMS DELHI INDIA. GS', 'consignee_phone' => ''],
            ['consignee_name' => 'KUBER ENTERPRISES', 'consignee_address' => '564/565/E GROUND FLOOR KATRA ISHWAR BHAWAN KHARI BAOLI DLEHI INDIA.', 'consignee_phone' => ''],
            ['consignee_name' => 'M/S KALU MAL MADAN LAL.', 'consignee_address' => '1074/75 GANDHI GALI JYOTI MARKET FATEHPURI DELHI 6 INDIA. , M/S KALU MAL MADAN LAL ADDRESS:1074/75 GANDHI GALI JYOTI MARKET FATEHPURI DELHI 6 INDIA. , M/S KALU MAL MADAN LAL ADDRESS: 1074/75 GANDHI GALI JYOTI MARKET FATEHPURI DELHI 6 INDIA. ', 'consignee_phone' => '+919899544908'],
            ['consignee_name' => 'NAKUL OVERSEAS', 'consignee_address' => '1ST FLOOR 535-36/6 KUCHA ATTAR SINGH MAJITH MANDI AMRITSAR INDIA. ', 'consignee_phone' => ''],
            ['consignee_name' => 'RAJA IMPEX', 'consignee_address' => '1026/24 RAJATIMPEX 2ND FLOOR GALI TELIAN TILAK BAZAR DELHI INDIA. , RAJATIMPEX NON-NEGOTIABLE UNLESS CONSIGNED "TO ORDER" ADD: 1026/24 2ND FLOOR GALI TELIAN TILAK BAZAR DELHI 110006 INDIA. FSSAl:10015011003137 FOR COMBINED TRANSPORT SHIPMENT OR PORT SHIPMENT', 'consignee_phone' => ''],
            ['consignee_name' => 'VKM EXPORTS', 'consignee_address' => 'PLOT NO: 227, INDUSTRIAL ESTATE, HSIIDC, PHASE-V, SECTOR- 53 KUNDLI, SONIPAT, HARYANA INDIA. GS', 'consignee_phone' => ''],
            ['consignee_name' => 'M/S MS DEVANSH INTERNATIONAL', 'consignee_address' => '73/71 ISHWAR MARKET GANDHI GALI FATEHPURI CENTRAL DELHI INDIA. FASI NO: 10018011005466:', 'consignee_phone' => '+919810886447'],
            ['consignee_name' => 'DALIP IMPEX', 'consignee_address' => 'SHOP NO-546/3 GROUND FLOOR KATRA ISHWAR BHAWAN KHARI BAOLI DELHI CENTRAL (DELHI) INDIA, SHOP N0-546/3 GROUND FLOOR KATRA ISHWAR BHAWAN KHARI BAOLI DELHI CENTRAL (DELHI) 110006 INDIA. , SHOP NO-546/3 GROUND FLOOR KATRA ISHWAR BHAWAN KHARI BAOLI DELHI CENTRAL (DELHI) 110006 INDIA.', 'consignee_phone' => '9958864956'],
            ['consignee_name' => 'Charu overseas', 'consignee_address' => '73/6 lshwar Market Gandhi Gali Fatehpuri Delhi FOR COMBINED TRANSPORT SH IPMENT OR PORT SHIPMENT', 'consignee_phone' => ''],
            ['consignee_name' => 'RAJDHANI AGRO FOODS', 'consignee_address' => '520, KATRA ISHWAR BHAWAN KHARI BAOLI DELHI INDIA. , 520, KATRA ISHWAR BHAWAN KHARI BAQLI DELHI 110006 INDIA.', 'consignee_phone' => '+919312832953'],
            ['consignee_name' => 'JHULAY LAL TRADING CO.', 'consignee_address' => '1117 THIRD FLOOR GANDHI GALI FATEH PURI N.D INDIA.', 'consignee_phone' => '+98076772950'],
            ['consignee_name' => 'BOLANI TREADING CO.', 'consignee_address' => 'A.64 KHASRA NO: 453 A BLOCK DUGGAL COLONY DEVLI ROAD KHAN PUR NEW DELHI SOUTH DELHI INDIA. , BOLANI TRADING CO ADDRESS: A-64, KHASRA NO. 453, A-BLOCK, DUGGAL COLONY, DEVLI ROAD, KHANPUR, NEW DELHI, SOUTH, DELHI, INDIA., BOLANI TRADING CO ADDRESS: A-64, KHASRA NO. 453, A-BLOCK, DUGGAL COLONY, DEVLI ROAD, KHANPUR, DELHI, 110062 INDIA.', 'consignee_phone' => '+918076772950'],
            ['consignee_name' => 'ANZA FOODS PRIVATE LIMITED', 'consignee_address' => '1117, FOURTH FLOOR, GANDHI GALI, FATEHPURI, N.D INDIA. GS', 'consignee_phone' => '+918851333904'],
            ['consignee_name' => 'VNC NUTRITION FOODS PVT LTD', 'consignee_address' => '1006-D, SAMAR ', 'consignee_phone' => '+919825607177'],
            ['consignee_name' => 'RICH VALLEY DRYFRUIT PRIVATE LIMITED', 'consignee_address' => '214, 2nd FLOOR, MADHUPURA COMMERCIAL COMPLEX MADHUPURA CIRCLE, MADHUPURA, AHMEDABAD Booking detail: GUJARAT INDIA', 'consignee_phone' => '+916359974979'],
            ['consignee_name' => 'PROVENTUS AGROCOM LIMITED', 'consignee_address' => 'UNIT 515, ATRIUM 215, WING \'C\', ANDHERI KURLA ROAD, ANDHERI EAST, MUMBAI 400 059 INDIA. , NON-NEGOTIABLE UNLESS CONSIGNED "TO ORDER• UNIT 515, ATRIUM 215, WING \'C\', ANDHERI KURLA ROAD, ANDHERI EAST, MUMBAI 400 059 INDIA. ', 'consignee_phone' => '+918828111547'],
            ['consignee_name' => 'DEV IMPEX', 'consignee_address' => 'DEVIMPEX ADDRESS: 46/11 NAVA KATRA KATRA ISHWAR BHAWAN KHARI BAOLI, DELHI INDIA. , 46/11 NAYA KATRA KATRA ISHWAR BHAWAN KHARI BAOLI, DELHI 110006 INDIA , 46/11 NAYA KATRA, KATRA ISHWAR BHAWAN, KHARI BAOLI, DELHI-110006 INDIA.', 'consignee_phone' => '+919999379060'],
            ['consignee_name' => 'RAJDHANI TRADERS', 'consignee_address' => '520/2 KATRA ISHWAR BHAWAN KHARI BAOLI DELHI INDIA. , 520/2 KATRA ISHWAR BHAWAN KHARI BAOLI, DELHI 110006, INDIA.', 'consignee_phone' => ''],
            ['consignee_name' => 'SHRI BALAJI TRADERS', 'consignee_address' => '2956, KATRA KHUSHAL RAI, KINARI BAZAR, DELHI INDIA.', 'consignee_phone' => '+919654698939'],
            ['consignee_name' => 'M/S DEVANSH INTERNATIONAL', 'consignee_address' => 'MS DEVANSH INTERNATIONAL ADD: 73/71 ISHWAR MARKET GANDHI GALI FATEHPURI CENTRAL DELHI INDIA. , M/ S MS DEVANSH INTERNATIONAL ADD: 73/71 lSHWAR MARKET GANDlll GALI FATEIIPURI CENTRAL D INDIA. FASSINO: 1001 80110054 66:', 'consignee_phone' => '+919810886447'],
            ['consignee_name' => 'MUSAWER ENTERPRISES', 'consignee_address' => 'FIRST FLOOR, 76, GANDHI GALI FATHEPURI, CENTRAL DELHI INDIA.', 'consignee_phone' => ''],
            ['consignee_name' => 'MEHRA INTERNATIONAL', 'consignee_address' => '580 B-IST FLOOR KATRA ISHWAR BHAWAN NEW DELHI INDIA, 580 B 1ST FLOOR KATRA ISHWAR BHAWAN NEW DELHI 110006 INDIA. , FOR COMBINED TRANSPORT SHIPMENT OR PORT SHIPMENT 580 B 1ST FLOOR KATRA ISHWAR BHAWAN NEW DELHI 110006 INDIA', 'consignee_phone' => '+919811076797'],
            ['consignee_name' => 'M/S S.K WOOLLENS', 'consignee_address' => 'A-78 \'SAOOL \'GANJ Bll<ANER RAJA5THAN INDIA GS', 'consignee_phone' => ''],
            ['consignee_name' => 'AFGHAN AGRO COMPANY', 'consignee_address' => 'P.0 .8ox:, Dubai, United Arab Emira tes w1.vw.genioshippin9.com 27 KATRA ISHWAR BHAWAN KHARI BAOLI DELHI 110006 INDIA.', 'consignee_phone' => ''],
            ['consignee_name' => 'ANJALI IMPEX', 'consignee_address' => '1ST FLOOR 2139 KATRA TABACOO, KHARI BAOLI, DELHI, NORTH DELHI INDIA. , 1ST FLOOR 2139 KATRA TАВАСОО, КHARI BAOLI, DELHI, NORTH DELHI, 110006 INDIA.', 'consignee_phone' => '+919212425295'],
            ['consignee_name' => 'LAKHDATAR FOODS', 'consignee_address' => 'GROUND FLOOR 564/565, KATRA ISHWAR BHAWAN, NEARFATEH PURI MASJID, KHARI BAOLI, DELHI, NORTH DELHI, INDIA , FOR COMBINED TRANSPORT SHIPMENT OR PORT SHIPMENT GROUND FLOOR 564/565, KATRA ISHWAR BHAWAN, NEAR FATEH PURI MASJID, KHARI BAOLI, DELHI, NORTH DELHI 110006, INDIA', 'consignee_phone' => '9212425295'],
            ['consignee_name' => 'CRYSTAL ENTERPRISES', 'consignee_address' => '304 MUSTAFA MANZIL, PLOT NO: 58/60 2ND STREET NAGPADA MUMBAI CENTRAL MUMBAI M.S IND/A. , 304 MUSTAFA MANZIL, PLOT NO: 58/60 2ND STREET NAGPADA MUMBAI CENTRAL MUMBAI M.S 400008 INDIA.', 'consignee_phone' => '+919892662285'],
            ['consignee_name' => 'AAYRA TRADING COMPANY', 'consignee_address' => '37A M-15, BB MILL ROAD MYSURU KARNATAKA, INDIA.', 'consignee_phone' => '+919980932573'],
            ['consignee_name' => 'JUGAL KISHORE TILOK CHAND', 'consignee_address' => '2210/213, SECOND FLOOR, AGARWAL MARKET, DELHI, CENTRAL, DELHI INDIA', 'consignee_phone' => ''],
            ['consignee_name' => 'H.S. INTERNATIONAL', 'consignee_address' => '1038-1039, F/F, GANDHI GALI, FATEHPURI, DELHI INDIA.', 'consignee_phone' => ''],
            ['consignee_name' => 'NEW FANCY TEXTILES', 'consignee_address' => '1119 GROUND FLOOR, GANDHI GALI FATEHPURI, DELHI, INDIA.', 'consignee_phone' => '+919582727110'],
            ['consignee_name' => 'KANAHIYA RAM BELA RAM', 'consignee_address' => 'OPPOSITE SETH BHANA MAL BUILDING SIRKI BAZAR BATHINDA PUNJAB INDIA.', 'consignee_phone' => '9855471987'],
            ['consignee_name' => 'RADHE SHYAM IMPEX', 'consignee_address' => 'SHOP NO: E-33 APMC, MASALA MARKET-1, PHASE-II, SECTOR-19, TURBHE, NAVI, MUMBAI, THANE, MAHARASHTRA INDIA.', 'consignee_phone' => '+918383889667'],
            ['consignee_name' => 'R.S INTERNATIONAL', 'consignee_address' => 'FOR COMBINED TRANSPORT SHIPMENT OR PORT SHIPMENT 1040/13 GROUND FLOOR SAI MARKET GANDHI GALI, DELHI INDIA. , 1040/13 GROUND FLOOR SAi MARKET GANDHI GAL DELHI 110006 INDIA.', 'consignee_phone' => '9213655112'],
            ['consignee_name' => 'KAMAL CHAND JAIN AND SONS', 'consignee_address' => '550 TO 552 G/F KATRA ISHWAR BHAWAN KHARI BAOLI, DELHI CENTRAL, INDIA', 'consignee_phone' => '9999057070'],
            ['consignee_name' => 'RISHABH ENTERPRISES', 'consignee_address' => 'SHOP NO: 14-A GADODIA MARKET, KHARI BAOLI, DELHI, INDIA.', 'consignee_phone' => ''],
            ['consignee_name' => 'KUKREJA FRUITS CO', 'consignee_address' => 'P1-ELOB OFFICE 511-A GROUND FLOOR KATRA ISHWAR BHAWAN KHARI E-11 F-09 HFZ - SHARJAH UNITED ARAB EMIRATES BAOLI DELHI INDIA, OLIVE CONTAINER LINE FZE 511-A GROUND FLOOR, KATRA ISHWAR BHAWAN KHARI BAOLI DELHI 110006 INOIA.', 'consignee_phone' => '+919958394456'],
            ['consignee_name' => 'SINDHWANI (INDIA) MERCHANDISE', 'consignee_address' => '439 KATRA MAIDGRAN KHARI BAOLI DELHI INDIA.', 'consignee_phone' => ''],
            ['consignee_name' => 'NIKHIL TRADERS', 'consignee_address' => '38 GROUND FLOOR GANDHI GALI FATEHPURI DELHI INDIA.', 'consignee_phone' => '9212119585'],
            ['consignee_name' => 'AKHIL ENTERPRISES', 'consignee_address' => '535 KATRA ISHWAR BHAWAN KHARI BAOLI DELHI INDIA', 'consignee_phone' => '9818364366'],
            ['consignee_name' => 'NIAZ GENERAL TRADING COMPANY.', 'consignee_address' => 'PLAT NO. 60 F/F, GANDHI GALI FATEHPURI, DELHI INDIA', 'consignee_phone' => '+918076354639'],
            ['consignee_name' => 'MOTI RAM AND SONS', 'consignee_address' => '519 KATRA ISHWAR BHAWAN KHARI BAOLI DELHI INDIA.', 'consignee_phone' => '+919811082140'],
            ['consignee_name' => 'DEEPTI ENTERPRISES', 'consignee_address' => '2214, GF, GALI HINGA BEGH, TILAK BAZAR, KHARI BAOLI, DELHI INDIA , 2214, GF, Gali Hinga Begh, Tilak Bazar, Khari Baoli, Delhi -110006', 'consignee_phone' => ''],
            ['consignee_name' => 'SUPERNOVA TRADERS PRIVATE LIMITED', 'consignee_address' => 'OLIVE CONTAINER LINE FZE FLAT NO. MG-1/59, FIRST FLOOR, VIKAS PURI, NEW DELHI, WEST DELHI, INDIA.', 'consignee_phone' => '+919811081878'],
            ['consignee_name' => 'RAJ ENTERPRISES', 'consignee_address' => '616, 2FLOOR, KATRA ISHWAR BHAWAN,KHARI BAOLI, DELHI, NORTH DELHI, DELHI', 'consignee_phone' => ''],
            ['consignee_name' => 'MANGLA OVERSEAS', 'consignee_address' => '441, GROUND FLOOR, KATRA MEDGRAN, KHARI BAOLI DELHl INDIA.', 'consignee_phone' => '+911149124603'],
            ['consignee_name' => 'NARENDER KUMAR ANIL KUMAR', 'consignee_address' => '6355 2ND FLOOR BIRI MARKET NAVA BANS KHARI BAOLI, DELHI INDIA', 'consignee_phone' => '01141500945'],
            ['consignee_name' => 'M/S KALRA IMPEX', 'consignee_address' => 'OLIVE CONTAINER LINE FZE SHOP NO: 511-512 GROUND FLOOR KATRA ISHWAR BHAWAN KHARI BAOLI DELHI INDIA. FASSAl:10018011004953', 'consignee_phone' => '9210461313'],
            ['consignee_name' => 'SHIVANI TRADING COMPANY', 'consignee_address' => 'NO: 489/208, MAIN ROAD, SHEVAPET, SALEM INDIA', 'consignee_phone' => '+914274961300'],
            ['consignee_name' => 'DIVYANSHI ENTERPRISES', 'consignee_address' => '104 SAMURAI BHAWAN SOP NO: 3 DEENANATH JI KI GALI CHANDPOLE BAZAR JAIPUR (RAJASTHAN) INDIA.', 'consignee_phone' => '+919929273994'],
            ['consignee_name' => 'SLG FOOD PROCESSING LLP', 'consignee_address' => 'C-1 50 OKHLA INDUSTRIAL AREA PHASE-1 NEW DELHI INDIA , C-150 OKHLA INDUSTRIAL AREA PHASE-! NEW DELHI 110020 INDIA.', 'consignee_phone' => '+919859856400'],
            ['consignee_name' => 'KOTHARI TRADING CO', 'consignee_address' => '1432/3 OPP FULPURA NEW MADHUPURA OUTSIDE DARIYAPUR GATE MADHUPURA AHMEDABAD INDIA.', 'consignee_phone' => '+919825856989'],
            ['consignee_name' => 'G.T JAYANTI AGROCHEM INDIA PVT LTD', 'consignee_address' => 'AKSHAYA 36 CARAT、 A-12, 1ST FLOOR, 950 POONAMALLE HIGH ROAD, CHENNAI, TAMIL NADU INDIA.', 'consignee_phone' => '+914435433965'],
            ['consignee_name' => 'GOLDEN NUTS TRADING LLC', 'consignee_address' => 'A/C NO.: 019101763826 IBAN NUMBER: AE880330000019101763826 MASHREQ BANK SWIFT CODE: BOMLAEAD MASHREQ BANK BRANCH: MURAQABAT BANK NAME: MASHREQ BANK PSC, P.O.BOX 1250, DUBAI, UAE', 'consignee_phone' => ''],
            ['consignee_name' => 'M/S STAR ALMOND COMPANY', 'consignee_address' => 'S.N-567-A. KATRA ISHWAR BHAWAN KHARI BAOLI, NORTH DELHI, DELHI INDIA. , S.N-567-A, KATRA ISHWAR BHAWAN KHARI BAOLI, NORTH DELHI, DELHI-110006 INDIA. (', 'consignee_phone' => '+919268653777'],
            ['consignee_name' => 'JDM ENTERPRISES', 'consignee_address' => '132/B, BEHIND GEETA VIHAR HOTEL, NEAR SPENCER\'S GYM, SANTACRUZ (EAST) MUMBAI INDIA. , 132/B,ROOM NO.2,KALINA VILLAGE, BEHIND GEETA VIHAR HOTEL, SANTACRUZ (EAST) MUMBAI-400029 INDIA.', 'consignee_phone' => ''],
            ['consignee_name' => 'M/S ABJOSH (MUNKKA) TRADING CO', 'consignee_address' => '559/9 KATRA ISHWAR BHAWAN KHARI BAOLI CHANDNI CHOWK DELHI INDIA.', 'consignee_phone' => '9818699798'],
            ['consignee_name' => 'CALIFORNIA AGRI NUTS CORPORATION', 'consignee_address' => '559 KATRA ISHWAR BHAWAN KHARI BAOLI DELHI INDIA.', 'consignee_phone' => ''],
            ['consignee_name' => 'UC METALS PVT LTD', 'consignee_address' => '303 KANE PLAZA OFF LINK ROAD CHINCHOLI BUKDER MALAD WEST MUMBAI INDIA.', 'consignee_phone' => ''],
            ['consignee_name' => 'HEMAL INTERNATIONAL.', 'consignee_address' => 'F-42 APMC MARKET-1 PHASE-2 VASHI NAVI MUMBAI INIDA.', 'consignee_phone' => '9830120939'],
            ['consignee_name' => 'D.N FORTUNE', 'consignee_address' => '562-563 1ST FLOOR KATRA ISHWAR BHAWAN KHARI BAOLI DELHI INDIA. , Name of company: D.N FORTUNE Add: 562-563 1ST FLOOR KATRA ISHWAR BHAWAN KHARI BAOLI DELHI 110006 INDIA.', 'consignee_phone' => '+911143559584'],
            ['consignee_name' => 'SHAURYA INTERNATIONAL', 'consignee_address' => 'PART OF PROPERTY NO 330 AND 332 KATRA HUSSAIN BUX KHARI BAOLI NEW DELHI INDIA.', 'consignee_phone' => '9212425295'],
            ['consignee_name' => 'LILA DRY FRUITS', 'consignee_address' => 'GR. FLOOR, W-22, MAIN KRISHI MANDI, MANDORE, JODHPUR, RAJASTHAN INDIA.', 'consignee_phone' => ''],
            ['consignee_name' => 'M/S SRI SRINIVAS EXPORTS', 'consignee_address' => '1076 2N FLOOR GANDHI GALI FATEH PURI DELHI CENTRAL DELHI INDIA. , 1076 2ND FLOOR GANDHI GALI FATEH PURI DELHI CENTRAL DELHI 110006 INDIА.', 'consignee_phone' => '+919899897966'],
            ['consignee_name' => 'HALWAI SONS', 'consignee_address' => 'F 30, APMC MARKET-1, VASHI, NAVI MUMBAI INDIA.', 'consignee_phone' => '9428566789'],
            ['consignee_name' => 'FRESITA FOOD PRIVATE LIMITED', 'consignee_address' => 'NEAR S.R.P. TRAINING CENTER, JUNAGADH JETPUR HIGHWAY, CHOKI (SORATH) GUJARAT, INDIA', 'consignee_phone' => '+919033647736'],
            ['consignee_name' => 'SKB NUTS PRIVATE LIMITED', 'consignee_address' => '(F.Y. 23-24) 533/34D KATRA ISHWAR BHAWAN KHARI BAOLI DELHI INDIA, (F.Y. 23-24) 533/34D KATRA ISHWAR BHAWAN, KHARI BAOLI DELHI 110006 INDIA.', 'consignee_phone' => '+919958425180'],
            ['consignee_name' => 'RIDDHI SIDDHI IMPEX', 'consignee_address' => 'RIDDHI SIDDH?? IMPEX NO: 19, VEERAPANDIAN KATTABOMAN STREE?, THIRUMURUGAN NAGAR, CHITLAPAKKAM', 'consignee_phone' => ''],
            ['consignee_name' => 'UNIVERSAL TRADERS', 'consignee_address' => 'CHENNAI INDIA. UNIVERSAL TRADERS 113,FIRST FLOOR, TILAK BAZAR CHOWK, DELHI 110006 INDIA.', 'consignee_phone' => ''],
            ['consignee_name' => 'RCA EXIM PRIVATE LIMITED', 'consignee_address' => '1112 2ND AND 3RD FLOOR GANDHI GALI FATEHPURI DELHI INDIA.', 'consignee_phone' => '+919999927864'],
            ['consignee_name' => 'HARSHA TRADING COMPANY', 'consignee_address' => '. F-5 APMC MARKET-1 PHASE-2 VASHI TURBHE NAVI MUMBAI INDIA.', 'consignee_phone' => '9967999500'],
            ['consignee_name' => 'NAMYA TRADING', 'consignee_address' => 'KRISHNA MOHAN PD MARUF GANJ, PATNA CITY, PATNA BIHAR-INDIA.', 'consignee_phone' => ''],
            ['consignee_name' => 'MUHANNA TOURISM AND TRAVELS LLC', 'consignee_address' => 'BANIYAS SQUARE LANDMARK PLAZA 1ST FLOOR SHOP F118 P.O BOX DEIRA DUBAI UAE Muhammadachakza22i@gmail.com ,+971 58 249 4205', 'consignee_phone' => ''],
            ['consignee_name' => 'AGHA LALA TRADING CO.LLC', 'consignee_address' => 'AL RAS DEIRA DUBAI U.A.E ', 'consignee_phone' => '+971561142468'],
            ['consignee_name' => 'Kanahiya ram Bela', 'consignee_address' => '', 'consignee_phone' => '30150170129855471987'],
            ['consignee_name' => 'CRAZY EXPORTS PRIVATE LIMITED', 'consignee_address' => '556 ,1ST FLOOR KATRA ISHWAR BHAWAN KHARI BAOLI CHANDANI CHOWK DELHI', 'consignee_phone' => '+919205817120'],
            ['consignee_name' => 'GANPATI INDUSTRIES', 'consignee_address' => '', 'consignee_phone' => '+919053246950'],
            ['consignee_name' => 'Kailash Chand Manoj Kumar', 'consignee_address' => '570 ground floor, Katra Ishwar Bhawan, Khari Baoli, Delhi, India.', 'consignee_phone' => '+919811135683'],
            ['consignee_name' => 'Preet Enterprise', 'consignee_address' => '', 'consignee_phone' => '9904887000'],
            ['consignee_name' => 'ANIL TRADING CO', 'consignee_address' => 'G/F, 611, KATRA ISHWAR BHAWAN, KHARI BAOLI, DELHI INDIA. atc2581@yahoo.in/', 'consignee_phone' => ''],
            ['consignee_name' => 'GOPAL INTERNATIONAL', 'consignee_address' => 'F-09,APMC MARKET-1, PHASE-2, MUDI BAZAR, VASHI, NAVI MUMBAI, INDIA', 'consignee_phone' => ''],
            ['consignee_name' => 'AL BADR DATES PRIVATE LIMITED', 'consignee_address' => 'A-103 F/F Abul Fazal Enclave I, Jamia Nagar,South East Delhi.', 'consignee_phone' => '+919667444566'],
            ['consignee_name' => 'DIVYANSHI ENTERPRISES', 'consignee_address' => '1. ', 'consignee_phone' => '99292739945'],
            ['consignee_name' => 'Kalra Impex Pvt Ltd', 'consignee_address' => 'M/S KALRA IMPEX SHOP NO: 511-512 GROUND FLOOR KATRA ISHWAR BHAWAN KHARI BAOLI DELHI INDIA.', 'consignee_phone' => '+911244016555'],
            ['consignee_name' => 'M/S RAJAT IMPEX', 'consignee_address' => 'RAJAT IMPEX ADD: 1026/24 2ND FLOOR GALI TELIAN TILAK BAZAR DELHI INDIA.', 'consignee_phone' => ''],
            ['consignee_name' => 'ROYAL NATURAL DRY FRUITS', 'consignee_address' => '/UMME HANY KHANAM ADRESS: 22/48, GROUND FLOOR NEAR PLATINA EXOTICA APARTMENT, DUBASIPALYA, BANGALORE-KARNATAKA INDIA.', 'consignee_phone' => ''],
            ['consignee_name' => 'LENSCRAFT DIGITAL STUDIO', 'consignee_address' => 'KUSHAK CITY, KHASRA NO. 108, HI RANK! ROAD, No: Date: HIRANKI, DELHI INDIA. !EC: 0504060520', 'consignee_phone' => '+919599056533'],
            ['consignee_name' => 'CROWN TRADERS FZE', 'consignee_address' => 'BLOCK B-B47-158 SHARJAH RESEARCH TECHNOLOGY AND INNOVATION PARK, FREE ZONE AUTHORITY, SHARJAH, UAE.', 'consignee_phone' => '+971507375984'],
            ['consignee_name' => 'RNGP Tradelink Pvt. Ltd.', 'consignee_address' => 'Near PAC Gate, Lakhanpur, Bhullanpur,Varanasi Uttar Pradesh GSTN No.09AALCR7418M1ZNI EC No. AALCR7418M Corpotare Iden(cid:415)ty Number U15339UP2022PTC161424', 'consignee_phone' => '9235665457'],
            ['consignee_name' => 'ABDOLRAHIM HAGHAYEGH SHIPPING AND CARGO L.L.C', 'consignee_address' => 'Corniche St Al Khan Al Hind tower #1508 Sharjah, UAE SJH +97165611942 finances@arhshipping.com', 'consignee_phone' => '+97165611942'],
            ['consignee_name' => 'K.L IMPORTS', 'consignee_address' => '41/5 1ST FLOOR GANDHI GALI KATRA ISHWAR BHAWAN NORTH DELHI DELHI INDIA. FSSAIN0:1001701100435~', 'consignee_phone' => ''],
            ['consignee_name' => 'UC METALS PVT LTD', 'consignee_address' => 'OFFICE ADDRESS: 303 KANE PLAZA LINK ROAD, CHIN CHO LI BUN DER, MIN SPACE, MALAD WEST, MUMBAI INDIA.', 'consignee_phone' => ''],
            ['consignee_name' => 'Green Galaxy', 'consignee_address' => '', 'consignee_phone' => '+919823020303'],
            ['consignee_name' => 'GHAI OVERSEAS', 'consignee_address' => 'MSGHAIOVERSEAS@GMAIL.COM', 'consignee_phone' => '+919810886447'],
            ['consignee_name' => 'D.N FORTUNE', 'consignee_address' => '562-5631ST FLOOR KATRA ISHWAR BHAWAN KHARI BAOLI DELHI INDIA ***/ AAPFD4354D TEC NO.', 'consignee_phone' => '+919899801223'],
            ['consignee_name' => 'UC Metals Pvt Ltd', 'consignee_address' => '10019011007147 add:562-563 1st floor katra ishwar bhawan khari baol delhi india Office Address: 303, Kane Plaza, Link Road, Chincholi Bunder, Mindspace, Malad West, Mumbai – 400064, India * , *', 'consignee_phone' => '+918460200291'],
            ['consignee_name' => 'MAAHIR INTERNATIONAL FZCO', 'consignee_address' => 'OFFICE NO: 1182-04, JAFZA ONE, TOWER-A, 11TH FLOOR, P.O-BOX, JEBEL ALI FREE ZONE, DUBAI, U.A.E.', 'consignee_phone' => ''],
            ['consignee_name' => 'M.VIDYA INTERNATIONAL', 'consignee_address' => '40/6 GROUND FLOOR GANDHI GALI FATEHPURI DELHI INDIA.', 'consignee_phone' => ''],
            ['consignee_name' => 'SIO International', 'consignee_address' => 'Ground Floor, Property No. 587–593 Katra Ishwar Bhawan, Kahri Baoli Chandni Chowk, New Delhi –, India * Legal Name: Ram Chand Gambhir * GS', 'consignee_phone' => '9859856400'],
            ['consignee_name' => 'JIMRI INTERNATIONAL TRADING FZC.', 'consignee_address' => 'OFFICE 11-153, BLDG D, AJMAN FREEZONE AJMAN UAE ', 'consignee_phone' => ''],
            ['consignee_name' => 'SATGUN EXIM LLP', 'consignee_address' => 'LLP Name: SATGUN EXIM LLP LLPIN: AAV‐1918 GS ', 'consignee_phone' => ''],
            ['consignee_name' => 'SIRAJ INTERNATIONAL LLP', 'consignee_address' => '– VERIFIED SUPPLIER PROFILE • Legal Name: SIRAJ INTERNATIONAL LLP • Entity Type: Limited Liability Partnership (LLP) • LLPIN: AAF-4598 REGISTERED ADDRESS 2587-88/6, Bazaar Gujran, Majith Mandi, Amritsar, Punjab – PARTNERS / MANAGEMENT • Manav Arora – Designated Partner • Raj Kumar Arora – Designated Partner , •', 'consignee_phone' => ''],
            ['consignee_name' => 'BRIDGE AGRO', 'consignee_address' => 'FirmT NELa.m e: 9: 8B9R9ID89G7E9 A66GRO ADDRESS : F-39, APMC Market 1, phase - 2, sec - 19, vashi, navi mumbai - 400 705. ', 'consignee_phone' => '']
        ];

        foreach ($consignees as $item) {
            DB::table('air_waybills')->insertGetId([
                'awb_number' => 'SEED-' . rand(100000, 999999),
                'airline_prefix' => '235',
                'serial_number' => (string)rand(10000000, 99999999),
                'shipper_name' => 'SKY ARIANA LTD',
                'shipper_address' => 'KABUL AFGHANISTAN',
                'consignee_name' => $item['consignee_name'],
                'consignee_address' => $item['consignee_address'],
                'consignee_phone' => $item['consignee_phone'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
