<?php

namespace Database\Seeders;

use App\Models\SavedCompany;
use Illuminate\Database\Seeder;

class SavedCompanySeeder extends Seeder
{
    public function run(): void
    {
        $sellers = [
            [
                'type' => 'seller',
                'company_name' => 'PAHLAWAN NOORI LTD',
                'address' => "Shorandam Industrial Park\nKandahar, Afghanistan",
                'phone' => '+93 707 070 975',
                'email' => 'info@pahlawannoori.com',
                'iec_code' => '27-1173', // Licence No
            ],
            [
                'type' => 'seller',
                'company_name' => 'HAYATULLAH KHAN FAZLI LTD',
                'address' => "Kandahar, Afghanistan",
                'phone' => '+93 705 122 800',
                'email' => '',
                'iec_code' => '27-2509',
            ],
            [
                'type' => 'seller',
                'company_name' => 'HABIB WALI NOORI LTD',
                'address' => "Kandahar, Afghanistan",
                'phone' => '+93 707 225 624',
                'email' => '',
                'iec_code' => '2429-27',
            ],
            [
                'type' => 'seller',
                'company_name' => 'RAHMAT NAZAR LTD',
                'address' => "Shorandam Industrial Area\nKandahar, Afghanistan",
                'phone' => '+93 700 300 979',
                'email' => '',
                'iec_code' => '682-27',
            ],
            [
                'type' => 'seller',
                'company_name' => 'NISAR AHMAD WAKEEL AHMAD LTD',
                'address' => "Kandahar, Afghanistan",
                'phone' => '+93 700 757 987',
                'email' => '',
                'iec_code' => '59297',
            ],
            [
                'type' => 'seller',
                'company_name' => 'TAHIR SULTANI LTD',
                'address' => "Kandahar, Afghanistan",
                'phone' => '+93 700 389 045',
                'email' => '',
                'iec_code' => '29241',
            ],
            [
                'type' => 'seller',
                'company_name' => 'NASRAT SHARIF LTD',
                'address' => "Shorandam Industrial Area\nKandahar, Afghanistan",
                'phone' => '+93 700 317 305',
                'email' => '',
                'iec_code' => '60530',
            ],
            [
                'type' => 'seller',
                'company_name' => 'NAJEB AMIN LTD',
                'address' => "Shorandam Industrial Area\nKandahar, Afghanistan",
                'phone' => '+93 700 308 086',
                'email' => '',
                'iec_code' => '27-975',
            ],
            [
                'type' => 'seller',
                'company_name' => 'NIAMATULLAH S/O SHAH MOHAMMAD',
                'address' => "Kandahar, Afghanistan",
                'phone' => '+93 700 849 277',
                'email' => '',
                'iec_code' => '39240',
            ],
            [
                'type' => 'seller',
                'company_name' => 'ABDUL RAZIQ MASHALLAH LTD',
                'address' => "Shorandam Industrial Area\nKandahar, Afghanistan",
                'phone' => '+93 711 111 707',
                'email' => '',
                'iec_code' => '27-6126',
            ],
            [
                'type' => 'seller',
                'company_name' => 'AHMAD SHAH TAIMUR LTD',
                'address' => "Kandahar, Afghanistan",
                'phone' => '+93 700 317 328',
                'email' => '',
                'iec_code' => '1150-27',
            ],
            [
                'type' => 'seller',
                'company_name' => 'SHAFI NASIB LTD',
                'address' => "KANDAHAR AFGHANISTAN",
                'phone' => '+93 700 189 595',
                'email' => 'shafinaseeb@gmail.com',
                'iec_code' => '85508',
            ],
            [
                'type' => 'seller',
                'company_name' => 'HIKMATULLAH S/O HAYATULLAH',
                'address' => "Shorandam Haji Zahir Market\nKandahar, Afghanistan",
                'phone' => '+93 700 332 876',
                'email' => '',
                'iec_code' => '63241',
            ],
            [
                'type' => 'seller',
                'company_name' => 'MILLAT INC LTD',
                'address' => "Kandahar, Afghanistan",
                'phone' => '+93 786 053 747',
                'email' => '',
                'iec_code' => '36335',
            ],
            [
                'type' => 'seller',
                'company_name' => 'RAHIMULLAH MIHRABI LTD',
                'address' => "Shorandam Industrial Area\nKandahar, Afghanistan",
                'phone' => '+93 703 027 088',
                'email' => '',
                'iec_code' => '62024',
            ],
            [
                'type' => 'seller',
                'company_name' => 'SARWAR HEMATYAR LTD',
                'address' => "KANDAHAR AFGHANISTAN",
                'phone' => '0093-785226400',
                'email' => '',
                'iec_code' => '27-10186',
            ],
            [
                'type' => 'seller',
                'company_name' => 'NOOR KHOSH BAHAR LTD',
                'address' => "Kandahar, Afghanistan",
                'phone' => '+93 700 355 851',
                'email' => '',
                'iec_code' => '81552',
            ],
            [
                'type' => 'seller',
                'company_name' => 'SAMI YAHYA LTD',
                'address' => "Shorandam Industrial Area\nKandahar, Afghanistan",
                'phone' => '+93 700 309 187',
                'email' => '',
                'iec_code' => '77163',
            ],
            [
                'type' => 'seller',
                'company_name' => 'QUDRATULLAH S/O MOHAMMAD NABI',
                'address' => "Kandahar, Afghanistan",
                'phone' => '+93 700 368 697',
                'email' => '',
                'iec_code' => '27-3488',
            ],
            [
                'type' => 'seller',
                'company_name' => 'TIJARATI SEHAT FARMAH LTD',
                'address' => "Kandahar, Afghanistan",
                'phone' => '+93 700 003 336',
                'email' => '',
                'iec_code' => '24476',
            ],
            [
                'type' => 'seller',
                'company_name' => 'ASIF KHAN TAWAKAL LTD',
                'address' => "Shorandam Industrial Area\nKandahar, Afghanistan",
                'phone' => '+93 707 070 465',
                'email' => '',
                'iec_code' => '2-5763',
            ],
            [
                'type' => 'seller',
                'company_name' => 'MOHAMMAD RAHIM ALMAS LTD',
                'address' => "Shorandam Industrial Area\nKandahar, Afghanistan",
                'phone' => '+93 706 495 439',
                'email' => '',
                'iec_code' => '55365',
            ],
            [
                'type' => 'seller',
                'company_name' => 'AHMAD WALI HADI LTD',
                'address' => "Shorandam Industrial Area\nKandahar, Afghanistan",
                'phone' => '+93 700 004 609',
                'email' => '',
                'iec_code' => '81083',
            ],
            [
                'type' => 'seller',
                'company_name' => 'SKY ARIANA LTD',
                'address' => "Mirwais Market, Kandahar\nHouse No 45, Road 3, Shar-E-Naw, Kabul, Afghanistan",
                'phone' => '+93 700 939 365',
                'email' => 'info@skyariana.com',
                'iec_code' => '2401-2198',
            ],
            [
                'type' => 'seller',
                'company_name' => 'SKY ARIANA TRADING LTD',
                'address' => "Industrial Zone 2\nKandahar, Afghanistan",
                'phone' => '+93-799-887766',
                'email' => 'trading@skyariana.com',
                'iec_code' => '27-44910',
            ],
            [
                'type' => 'seller',
                'company_name' => 'ARIANA AFGHAN TRADING LTD',
                'address' => "Kabul Industrial Park\nKabul, Afghanistan",
                'phone' => '+93-700-112233',
                'email' => 'contact@arianaafghan.com',
                'iec_code' => '27-09921',
            ],
            [
                'type' => 'seller',
                'company_name' => 'MOHAMMAD SADIQ SADIQI LTD',
                'address' => "Shorandam Industrial Area\nKandahar, Afghanistan",
                'phone' => '+93 700 339 649',
                'email' => '',
                'iec_code' => '2935-27',
            ],
            [
                'type' => 'seller',
                'company_name' => 'NAJIB ASAD LTD',
                'address' => "Shorandam Industrial Area\nKandahar, Afghanistan",
                'phone' => '+93 707 070 975',
                'email' => '',
                'iec_code' => '88619',
            ],
            [
                'type' => 'seller',
                'company_name' => 'NEW YAQOUBI LTD',
                'address' => "Shorandam Industrial Area\nKandahar, Afghanistan",
                'phone' => '+93 700 303 372',
                'email' => '',
                'iec_code' => '590-27',
            ],
            [
                'type' => 'seller',
                'company_name' => 'HAYAT NOOR ESMAT LTD',
                'address' => "Kandahar, Afghanistan",
                'phone' => '+93 703 893 271',
                'email' => '',
                'iec_code' => '2929-27',
            ],
            [
                'type' => 'seller',
                'company_name' => 'FAZALULHAQ QANI LTD',
                'address' => "Kandahar, Afghanistan",
                'phone' => '+93 702 933 579',
                'email' => '',
                'iec_code' => '2943-27',
            ],
            [
                'type' => 'seller',
                'company_name' => 'KHOGIYANI INTERNATIONAL LTD',
                'address' => "Shorandam Industrial Area\nKandahar, Afghanistan",
                'phone' => '+93 700 367 075',
                'email' => '',
                'iec_code' => '27-2309',
            ],
            [
                'type' => 'seller',
                'company_name' => 'KABUL DANISH TRADING COMPANY',
                'address' => "Mandawi Kabul District-1\nKabul, Afghanistan",
                'phone' => '+93 799 557 273',
                'email' => '',
                'iec_code' => '68259',
            ],
            [
                'type' => 'seller',
                'company_name' => 'AKHTAR AYAZAI LTD',
                'address' => "Shorandam Industrial Area\nKandahar, Afghanistan",
                'phone' => '+93 786 855 210',
                'email' => '',
                'iec_code' => '795-27',
            ],
            [
                'type' => 'seller',
                'company_name' => 'MANSOOR AYAZAI LTD',
                'address' => "Shorandam Industrial Area\nKandahar, Afghanistan",
                'phone' => '+93 786 855 210',
                'email' => '',
                'iec_code' => '792-27',
            ],
            [
                'type' => 'seller',
                'company_name' => 'ZAHIR QADARI LTD',
                'address' => "Kandahar, Afghanistan",
                'phone' => '+93 703 045 659',
                'email' => '',
                'iec_code' => '253-24',
            ],
            [
                'type' => 'seller',
                'company_name' => 'KHUDAI RAHIM S/O NAZAR MOHAMMAD',
                'address' => "Kandahar, Afghanistan",
                'phone' => '+93 700 000 695',
                'email' => '',
                'iec_code' => '56512',
            ],
            [
                'type' => 'seller',
                'company_name' => 'NAWI ARGHAND LTD',
                'address' => "Kandahar, Afghanistan",
                'phone' => '+93 786 053 747',
                'email' => '',
                'iec_code' => '2321-27',
            ],
            [
                'type' => 'seller',
                'company_name' => 'RAHIM WAHEDI TRADING COMPANY',
                'address' => "Kandahar, Afghanistan",
                'phone' => '+93 700 302 682',
                'email' => '',
                'iec_code' => '61259',
            ],
            [
                'type' => 'seller',
                'company_name' => 'WASELA LTD',
                'address' => "Kandahar, Afghanistan",
                'phone' => '+93 700 302 317',
                'email' => '',
                'iec_code' => '444-27',
            ],
            [
                'type' => 'seller',
                'company_name' => 'KARAMAT SULAIMAN LTD',
                'address' => "First Makroryan\nKabul, Afghanistan",
                'phone' => '+93 700 302 420',
                'email' => '',
                'iec_code' => '13154',
            ],
            [
                'type' => 'seller',
                'company_name' => 'NASIB OBID AKBARI LTD',
                'address' => "MANDAVI MARKET, BUILDING 12\nKABUL AFGHANISTAN",
                'phone' => '+93788998877',
                'email' => 'sales@nasibobidakbari.com',
                'iec_code' => '27-8899',
            ],
            [
                'type' => 'seller',
                'company_name' => 'AFGHAN AGRO COMPANY',
                'address' => "SUITE 402, AGRO TOWER, BAZAR MAZAR\nMAZAR-I-SHARIF AFGHANISTAN",
                'phone' => '+93700112233',
                'email' => 'contact@afghanagro.com',
                'iec_code' => '27-4401',
            ],
        ];

        $buyers = [
            [
                'type' => 'buyer',
                'company_name' => 'Uttam Chand Rakesh Kumar Private Limited',
                'address' => "573, Katra Ishwar Bhawan, Khari, Baoli\nDelhi-110006(India)",
                'phone' => '011-45784868',
                'email' => 'akshaykbhatia@hotmail.com',
                'gst_no' => '07AADCU4808L1Z2',
                'fssai_no' => '13324999000404',
                'iec_code' => 'AADCU4808L',
            ],
            [
                'type' => 'buyer',
                'company_name' => 'Nutriello International',
                'address' => "Plot No. 183, Deenanath Ji Ka Rasta,\nBarathio Ki Gali Chandpole Bazar, Jaipur,\nRajasthan, India - 302001",
                'phone' => '+918890430290',
                'email' => 'nutrielloint@gmail.com',
                'gst_no' => '08AMZPA5432D1Z1',
                'fssai_no' => '10019011000123',
                'iec_code' => 'AMZPA5432D',
            ],
            [
                'type' => 'buyer',
                'company_name' => 'VIRKINE TRADEXIM PRIVATE LIMITED',
                'address' => "BUILDING NO.2/2 AND 2/1 4TH FLOOR,\nCHHATARPUR MAIN ROAD, NEW DELHI, INDIA - 110074",
                'phone' => '+918586921182',
                'email' => 'per.virkinetradexim@gmail.com',
                'gst_no' => '07AAJCV7506N1ZQ',
                'fssai_no' => '13325999000430',
                'iec_code' => 'AAJCV7506N',
            ],
            [
                'type' => 'buyer',
                'company_name' => 'DATES FACTORY',
                'address' => "1789, GROUND FLOOR, ZEENAT MAHAL BAZAR\nLAL KUAN NEW DELHI, DELHI - 110006",
                'phone' => '+919654949177',
                'email' => 'datesfactory2025@gmail.com',
                'gst_no' => '07AORPA4267N1Z8',
                'fssai_no' => '13325999000444',
                'iec_code' => 'AORPA4267N',
            ],
            [
                'type' => 'buyer',
                'company_name' => 'PT AGRO GUNAJAYA SENTOSA',
                'address' => "KLAMPIS (KPP GUBENG) RUKO KLAMPIS MEGAH,\nJL. KLAMPIS JAYA BLOK B-20 KLAMPIS NGASEM,\nKEC. SUKOLILO SURABAYA, EAST JAVA INDONESIA",
                'phone' => '085885555888',
                'email' => 'agrogunajayasentos@gmail.com',
                'gst_no' => '1000000001203093',
                'fssai_no' => '',
                'iec_code' => '1000000001203093',
            ],
            [
                'type' => 'buyer',
                'company_name' => 'MANOCHA ENTERPRISES',
                'address' => "26 GROUND FLOOR KATRA ISHWAR BHAWAN\nGANDHI GALI KHARI BAOLI DELHI 110006 INDIA",
                'phone' => '+9810355677',
                'email' => 'RMANOCHA31@GMAIL.COM',
                'gst_no' => '07MRPM3332J1ZG',
                'fssai_no' => '10015011002643',
                'iec_code' => 'MRPM3332J',
            ],
            [
                'type' => 'buyer',
                'company_name' => 'HALWAI SONS EXPORTS',
                'address' => "Plot 42, Dry Fruit Market\nKhari Baoli, Delhi-110006 INDIA",
                'phone' => '011-23948811',
                'email' => 'info@halwaisons.com',
                'gst_no' => '07AAAFH1234F1Z1',
                'fssai_no' => '10019011005541',
                'iec_code' => 'AAAFH1234F',
            ],
            [
                'type' => 'buyer',
                'company_name' => 'DIPAK TRADING CO.',
                'address' => "GROUND FLOOR, F-29, MARKET-1, PHASE-2 APMC,\nSECTOR -19, VASHI, TURBHE, NAVI MUMBAI, THANE MAHARASHTRA INDIA",
                'phone' => '011-43219988',
                'email' => 'dipaktrading@gmail.com',
                'gst_no' => '07AABCD5678K1Z5',
                'fssai_no' => '13322001004412',
                'iec_code' => 'AABCD5678K',
            ],
            [
                'type' => 'buyer',
                'company_name' => 'BRIDGE AGRO PRODUCTS PVT LTD',
                'address' => "Building B, Dry Fruit Complex\nAzadpur, Delhi-110033 INDIA",
                'phone' => '011-27654321',
                'email' => 'import@bridgeagro.in',
                'gst_no' => '07AABCB9988E1Z9',
                'fssai_no' => '10018011009988',
                'iec_code' => 'AABCB9988E',
            ],
            [
                'type' => 'buyer',
                'company_name' => 'GOPAL INTERNATIONAL',
                'address' => "415, Katra Ishwar Bhawan\nKhari Baoli, Delhi-110006 INDIA",
                'phone' => '011-45678901',
                'email' => 'gopalintl@yahoo.com',
                'gst_no' => '07AABCG1122D1Z3',
                'fssai_no' => '10017011003322',
                'iec_code' => 'AABCG1122D',
            ],
            [
                'type' => 'buyer',
                'company_name' => 'KNIGHT TRADING COMPANY',
                'address' => "499-500, KATRA ISHWAR BHAWAN\nKHARI BAOLI, DELHI - 110006 INDIA",
                'phone' => '+919560020114',
                'email' => 'knighttrading@gmail.com',
                'gst_no' => '07AAJPK8987D1Z8',
                'fssai_no' => '10015011003137',
                'iec_code' => '0595032745',
            ],
            [
                'type' => 'buyer',
                'company_name' => 'SAFFRON HOME LLP',
                'address' => "GROUND FLOOR, SHOP A, 18 KIRANA BHAWAN,\nAUDIAPPA NAICKEN STREET, SOWCARPET, CHENNAI,\nTAMILNADU 600001 INDIA",
                'phone' => '+919840526511',
                'email' => 'saffronhomellp@gmail.com',
                'gst_no' => '33AABCS1234F1Z5',
                'fssai_no' => '10017011004358',
                'iec_code' => '3304050607',
            ],
            [
                'type' => 'buyer',
                'company_name' => 'KAILASH TRADERS',
                'address' => "535/2, KATRA ISHWAR BHAWAN\nKHARI BAOLI, DELHI - 110006 INDIA",
                'phone' => '01145680700',
                'email' => 'kailashtraders@gmail.com',
                'gst_no' => '07AAAFK1122G1Z4',
                'fssai_no' => '10016011004211',
                'iec_code' => 'AAAFK1122G',
            ],
            [
                'type' => 'buyer',
                'company_name' => 'RAJA DRY FRUITS',
                'address' => "First Floor, 602-603, Katra Ishwar Bhawan\nKhari Baoli, North Delhi, Delhi - 110006 INDIA",
                'phone' => '9811526548',
                'email' => 'rajadryfruit@gmail.com',
                'gst_no' => '07AABCR9900H1Z6',
                'fssai_no' => '10018011002233',
                'iec_code' => 'AABCR9900H',
            ],
            [
                'type' => 'buyer',
                'company_name' => 'MEHRA DRY FRUIT IMPEX',
                'address' => "1074/75 GANDHI GALI FATEHPURI\nNEW DELHI 110006 INDIA",
                'phone' => '+9311076797',
                'email' => 'mehradryfruits@gmail.com',
                'gst_no' => '07CPUPM4144Q1ZY',
                'fssai_no' => '10019011006677',
                'iec_code' => 'CPUPM4144Q',
            ],
            [
                'type' => 'buyer',
                'company_name' => 'SIDDHARTH IMPORTS PVT LTD',
                'address' => "581 KATRA ISHWAR BHAWAN\nKHARI BAOLI DELHI 110006 INDIA",
                'phone' => '+919810193840',
                'email' => 'siddharthimports@gmail.com',
                'gst_no' => '07AABCS7788J1Z9',
                'fssai_no' => '10017011008899',
                'iec_code' => 'AABCS7788J',
            ],
            [
                'type' => 'buyer',
                'company_name' => 'ANZA FOODS PRIVATE LIMITED',
                'address' => "1117, FOURTH FLOOR, GANDHI GALI\nFATEHPURI, NEW DELHI 110006 INDIA",
                'phone' => '+918851333904',
                'email' => 'anzafoods@gmail.com',
                'gst_no' => '07AABCA5566K1Z2',
                'fssai_no' => '10020011001122',
                'iec_code' => 'AABCA5566K',
            ],
            [
                'type' => 'buyer',
                'company_name' => 'HUNNY ENTERPRISES',
                'address' => "SHOP NO: 25, GANDHI GALI\nFATEHPURI DELHI 110006 INDIA",
                'phone' => '9654155525',
                'email' => 'hunnyenterprises@gmail.com',
                'gst_no' => '07AABCH3344L1Z3',
                'fssai_no' => '10016011007788',
                'iec_code' => 'AABCH3344L',
            ],
            [
                'type' => 'buyer',
                'company_name' => 'ELECO GENERAL TRADING L.L.C',
                'address' => "HAJI YOUSAF HUSSAIN SADIQ BUILDING, SHOP NO.7\nAL RAS, DUBAI, UAE",
                'phone' => '+971 50 123 4567',
                'email' => 'elecotrading@gmail.com',
                'gst_no' => '104169882800003',
                'fssai_no' => '',
                'iec_code' => '104169882800003',
            ],
            [
                'type' => 'buyer',
                'company_name' => 'YAAQOUB HAMDAN FOODSTUFF TRADING CO LLC',
                'address' => "SHOP NO: 28 AL HAWAI BUILDING\nAL RAS STREET DEIRA DUBAI UAE",
                'phone' => '+971 50 987 6543',
                'email' => 'yaaqoubhamdan@gmail.com',
                'gst_no' => '100340961000003',
                'fssai_no' => '',
                'iec_code' => '100340961000003',
            ],
            [
                'type' => 'buyer',
                'company_name' => 'NOOR JANAN GENERAL TRADING L.L.C',
                'address' => "Baniyas Square, Deira, Dubai\nAl Awais Bldg. No 14, Dubai, UAE",
                'phone' => '+971 50 445 6677',
                'email' => 'noorjanan@gmail.com',
                'gst_no' => '100440986600003',
                'fssai_no' => '',
                'iec_code' => '100440986600003',
            ],
            [
                'type' => 'buyer',
                'company_name' => 'LAKHDATAR FOODS',
                'address' => "GROUND FLOOR 564/565, KATRA ISHWAR BHAWAN\nNEAR FATEH PURI MASJID, KHARI BAOLI, DELHI - 110006 INDIA",
                'phone' => '9212425295',
                'email' => 'lakhdatarfoods@gmail.com',
                'gst_no' => '07AABCL8899M1Z5',
                'fssai_no' => '10018011003344',
                'iec_code' => 'AABCL8899M',
            ],
        ];

        foreach (array_merge($sellers, $buyers) as $data) {
            SavedCompany::updateOrCreate(
                ['company_name' => $data['company_name']],
                $data
            );
        }
    }
}
